# vi: sw=2 ts=2 sts=2 expandtab

language: python
os:
  - linux
#   - osx
python:
  #  - "2.6"
  - "2.7"
    # - "3.2"
    # - "3.3"
  - "3.4"
    # - "3.5"
    # - "pypy"

before_install:
  - echo $TRAVIS_OS_NAME
  # Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then apt-cache search swig; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y swig3.0; fi
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install swig; fi
install:
  - python setup.py build
  - python setup.py install

script: nosetests
