# vi: sw=2 ts=2 sts=2 expandtab

sudo: false
language: python
os:
  - linux
#   - osx
addons:
  apt:
    # sources:
    #   -
    packages:
      - swig2.0
python:
  #  - "2.6"
  - "2.7"
    # - "3.2"
    # - "3.3"
  - "3.4"
    # - "3.5"
    # - "pypy"

before_install:
  - echo $TRAVIS_OS_NAME
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install swig; fi
install:
  - python setup.py build
  - python setup.py install

script: nosetests
