# vi: sw=2 ts=2 sts=2 expandtab

sudo: false
language: python
os:
  - linux
#   - osx
addons:
  apt:
    packages:
      # for linuxbrew
      - build-essential
      - curl
      - git
      - m4
      - ruby
      - texinfo
      - libbz2-dev
      - libcurl4-openssl-dev
      - libexpat-dev
      - libncurses-dev
      - zlib1g-dev

python:
  #  - "2.6"
  - "2.7"
    # - "3.2"
    # - "3.3"
  - "3.4"
    # - "3.5"
    # - "pypy"

before_install:
  - echo $TRAVIS_OS_NAME
  # install linuxbrew on linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH="$HOME/.linuxbrew/bin:$PATH"; fi
  - pip install setuptools nose coverage
  - brew update
  - brew install swig
install:
  - python setup.py build --force
  - python setup.py install

script: nosetests -v -w tests --with-coverage --cover-package=Box2D
