# vi: sw=2 ts=2 sts=2 expandtab

language: python
os:
  - linux
#   - osx
python:
  #  - "2.6"
  - "2.7"
    # - "3.2"
    # - "3.3"
  - "3.4"
    # - "3.5"
    # - "pypy"

before_install:
  - echo $TRAVIS_OS_NAME
  - pip install setuptools nose coverage
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget http://mirrors.kernel.org/ubuntu/pool/main/s/swig/swig3.0_3.0.7-2ubuntu1_amd64.deb; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo dpkg --install swig3.0_3.0.7-2ubuntu1_amd64.deb; fi
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install swig; fi
install:
  - python setup.py build --force
  - python setup.py install

script: nosetests -v -w tests --with-coverage --cover-package=Box2D
